version: '3'

services:
  app:
    env_file:
      - .env
    build: .
    volumes:
      - sqlite_data:/app/database  # Монтируем том для SQLite
      - bot_lock:/tmp  # Общий том для файла-локера
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
volumes:
  sqlite_data:  # Создаем том для SQLite
  bot_lock: