version: '3'

services:
  app:
    env_file:
      - .env
    build: .
    volumes:
      - sqlite_data:/app  # Монтируем том для SQLite
    restart: unless-stopped

volumes:
  sqlite_data:  # Создаем том для SQLite