version: '3'

services:
  app:
    env_file:
      - .env
    build: .
    volumes:
      - ./data:/app/data  # Используем bind mount вместо volume
    restart: unless-stopped

# volumes:
#   sqlite_data:  # Создаем том для SQLite